### ISSUE TITLE
Add StatementResponse to the api

### ISSUE THREAD

**Issue by gklijs** [naamancurtis/ksql-db-rs#1]
Hi, just used your crate in https://github.com/gklijs/ksqlDB-GraphQL-poc/tree/main/rust-data-creator which is a wip. It worked great, but for now I just use serde_json::Value as the return type fro the `execute_statement`. I think it would be nice if the `StatementResponse` which is already defined in the Examples would be part of the api.

There might be valid reason not to do this. Like it might break, but you could always use another return type if you wish to do so.

**Comment by naamancurtis** [comment]
Hey,

Glad it worked well, the `execute_statement` API is deliberately a bit lower-level and was more so intended for people who were sending multiple statements in the same query string - as the different statements return different response structures typing it is a bit tricker, eg. you might send `CREATE ...; TERMINATE...; LIST QUERIES ...;` statements together. So that API was left completely open for the user to type the response

From what I can see on your app, most of your queries are isolated, did you take a look at [KsqlDB::create](https://docs.rs/ksqldb/0.1.0-alpha.6/ksqldb/struct.KsqlDB.html#method.create)? 

As far as I'm aware, that should expose a complete response structure inline with what KSQL actually sends back and is actually more detailed than the `StatementResponse` in the example? Or does that not fit the use case you have in mind?

I think that API would also let you create your table and 3 streams with a single http request - if that's something you want to do.

**Comment by gklijs** [comment]
Thanks for the explanation, I'll give `create` a try and you know how it goes. Just FYI I'm just started using KsqlDB, and didn't even look up the actual Rest api yet.

**Comment by gklijs** [comment]
It worked nicely, I already refactored a bit, so the ksqldb part is now in a separate module. https://github.com/gklijs/ksqlDB-GraphQL-poc/blob/main/rust-data-creator/src/ksqldb.rs I shared it on the Confluent slack, and they also send a tweet about it https://twitter.com/ksqlDB/status/1377640035957186568.
Nice work, thanks a lot.

**Comment by naamancurtis** [comment]
Glad to hear it! Awesome stuff!

Thanks, I really appreciate the shout out. Let me know if you come across any features you'd like to see in the crate.
